### ISSUE TITLE
Error when install using docker-compose

### ISSUE THREAD

**Issue by sunrisewestern** [Merck/mRNAid#10]
=> ERROR [mrnaid-worker 6/9] RUN conda env update -n base -f ./flask_app/environment.yml     && rm -rf /tmp/*   550.5s

#0 544.6
#0 544.6 UnsatisfiableError: The following specifications were found to be incompatible with a past
#0 544.6 explicit spec that is not an explicit spec in this operation (pip):
#0 544.6
#0 544.6   - flask-cors=3.0.10 -> python[version='>=3.6'] -> pip
#0 544.6   - flask=2.0.1 -> python[version='>=3.6'] -> pip
#0 544.6   - pip=21.0.1 -> setuptools
#0 544.6   - python[version='>=3.7,<3.8'] -> pip -> setuptools
#0 544.6   - uwsgi=2.0.19.1 -> python[version='>=3.9,<3.10.0a0'] -> pip
#0 544.6   - viennarna=2.4.17 -> python[version='>=3.7,<3.8.0a0'] -> pip
#0 544.6

**Comment by sunrisewestern** [comment]
#11 A work-around fix here.

**Comment by nikita-vostrosablin** [comment]
Hello, thanks for reporting, we will work on fixing the issue with docker installation

**Comment by nikita-vostrosablin** [comment]
Fixed in https://github.com/Merck/mRNAid/pull/14
