### ISSUE TITLE
Error when running docker-compose

### ISSUE THREAD

**Issue by generalextraneous** [Merck/mRNAid#12]
When I attempt to run docker-compose up --build I receive the following conda error
 > [mrnaid-main-backend 6/9] RUN conda env update -n base -f ./flask_app/environment.yml     && rm -rf /tmp/*     && conda clean --all:
#0 2.447 Collecting package metadata (repodata.json): ...working... Killed
------
failed to solve: executor failed running [/bin/sh -c conda env update -n base -f ./flask_app/environment.yml     && rm -rf /tmp/*     && conda clean --all]: exit code: 137

**Comment by nikita-vostrosablin** [comment]
Hello, thanks for reporting, we will work on fixing the issues with docker installation

**Comment by nikita-vostrosablin** [comment]
Fixed in https://github.com/Merck/mRNAid/pull/14
