### ISSUE TITLE
Error when install using docker-compose

### ISSUE THREAD

**Issue by allenzhengsh** [Merck/mRNAid#13]
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (python):

  - flask-cors=3.0.10 -> flask[version='>=0.9'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7|>=3.6,<3.7.0a0|3.4.*|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
  - flask-cors=3.0.10 -> python[version='>=3.6'] -> pip
  - flask=2.0.1 -> click[version='>=7.1.2'] -> python[version='>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.7']
  - flask=2.0.1 -> python[version='>=3.6'] -> pip
  - pip=21.0.1 -> python[version='>=3.6']
  - pip=21.0.1 -> setuptools -> python[version='!=3.0,!=3.1,!=3.2,!=3.3,!=3.4|2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.7|>=3.8|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.11,<3.12.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*|2.7.*|>=3.6']
  - python[version='>=3.7,<3.8'] -> pip -> setuptools
  - uwsgi=2.0.19.1 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0']
  - uwsgi=2.0.19.1 -> python[version='>=3.9,<3.10.0a0'] -> pip
  - uwsgi=2.0.19.1 -> python_abi=3.9[build=*_cp39] -> python[version='3.6.*|3.8.*|3.9.*|3.7.*']
  - viennarna=2.4.17 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - viennarna=2.4.17 -> python[version='>=3.7,<3.8.0a0'] -> pip
  - viennarna=2.4.17 -> python_abi=3.7[build=*_cp37m] -> python[version='2.7.*|3.6.*|3.7.*|3.8.*|3.9.*']

What version of Conda is recommended for Ubuntu 20.04？ thanks

**Comment by nikita-vostrosablin** [comment]
Fixed in https://github.com/Merck/mRNAid/pull/14
