### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by kvetab** [Merck/mRNAid#2]
Hi, 
to keep track, I'm listing the issues we ran into during deployment.

- Line 140 in the Readme should contain `cp -R ./build/* /usr/share/nginx/html`
- In frontend/.env, the third line needed to be changed to `REACT_APP_API_URL=/api/v1`
- The frontend doesn't show error messages form backend (e.g. "Entropy window is missing")
- Entropy window parameter is not required in the input form, but submission fails when it's not filled in.
- Optimization returns too many sequences.
- The nginx config needed to be changed:

```
server{
    ...
    server_name mrnaid.dichlab.org;

    location /api/v1 {
        ...
        uwsgi_pass 127.0.0.1:8080;
        ...
    }
}
```

Mentioning @prihoda for reference. Maybe some of these fixes could also be in a separate repo, as David suggested.

**Comment by nikita-vostrosablin** [comment]
all points except nginx config are addressed in PR https://github.com/Merck/mRNAid/pull/3
